apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  type: LoadBalancer
  ports:
  - port: 8009
    targetPort: 80
  selector:
    app: hello-kube
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: rujuvajani/helloworld:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8005
